name: Use the data

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
